version: '3'

services:
  nginx:
      image: nginx:latest
      ports:
        - "80:80"
        - "443:443"
      restart: always
      volumes:
         - ./nginx/conf:/etc/nginx/conf.d:ro
         - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params:ro
         - ./static:/static:ro
         - ./certbot/www:/var/www/certbot/:ro
         - ./certbot/conf/:/etc/nginx/ssl/:ro
      depends_on:
        - python

  db:
      image: mysql:5.7
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      ports:
        - "3306:3306"
      env_file:
        - mysql_environment.env
      environment:
        TZ: 'Asia/Tokyo'
      volumes:
        - db-store:/var/lib/mysql
  python:
      build: ./python
      command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/mylog.log
      env_file:
        - mysql_environment.env
      volumes:
        - ./src:/code
        - ./static:/static
      expose:
        - "8001"
      depends_on:
        - db

  certbot:
      image: certbot/certbot:latest
      volumes:
        - ./certbot/www/:/var/www/certbot/:rw
        - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  db-store: